str_input=input("숫자입력:")
num_input=float(str_input)

print()
print(num_input,"inch")
print((num_input*2.54),"cm")

str_input=input("원의 반지름 입력:")
num_input=float(str_input)
print()
print("반지름:",num_input)
print("둘레:",2*3.14*num_input)
print("넓이:",3.14*num_input**2)

a=input("문자열 입력:")
b=input("문자열 입력:")
print(b,a)
output_a="{:5d}".format(52)
print(output_a)
output_f="{:+d}".format(52)
output_g="{:+d}".format(-52)
output_h="{: d}".format(52)
output_i="{: d}".format(-52)
print(output_f)
print(output_g)
print(output_h)
print(output_i)
